ENCODING = "cp1252"
SEPARATOR = ";"

PERSON_COLUMNS = [
    "Código",
    "CPF/CNPJ",
    "Telefone",
    "Nome",
    "Observação",
    "Como chegou",
    "Tipo",
    "RG",
    "Data Nascimento",
    "Local de nascimento",
    "Sexo",
    "Salário",
    "Órgão emissor",
    "Estado civil",
    "Profissão",
    "Escolaridade",
    "Nacionalidade",
    "Razão Social",
    "Núm. Inscr. Estadual",
    "Núm. Inscr. Municipal",
    "CPF do responsável",
    "RG do responsável",
    "Nome do responsável",
    "CEP",
    "Cidade",
    "Bairro",
    "Estado",
    "Rua",
    "Número",
    "Complemento",
    "Num apto",
    "Num. Cond.",
    "Núm. Piso",
    "Núm.Bloco",
    "Obs. Cond.",
    "Núm. Lote",
    "Núm. bloco",
    "Cobrar taxa de bco",
    "Imobiliária",
    "Departamento",
    "Cargo",
    "Possui acesso ao sistema",
    "login",
    "SenhaMD5",
    "Tipo captador",
    "Não trocar no envio automático de e-mail",
    "% de comissão",
    "% Comissao Loc",
    "Área de atuação",
    "Creci",
    "Vínculo com a imobiliária",
    "Tipo corretor",
    "Piso salarial",
    "Tipo serviço prestado",
    "CPF Cônjuge",
    "Nome cônjuge",
    "RG Cônjuge",
]

EMAIL_COLUMNS = [
    "Código",
    "Email",
]

PHONE_COLUMNS = [
    "Código",
    "DDD",
    "Telefone",
    "Tipo",
]
